version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=oak-jwks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - '.database/init:/docker-entrypoint-initdb.d'

  # elasticmq:
  #   image: softwaremill/elasticmq
  #   volumes:
  #     - ./elasticmq.conf:/opt/elasticmq.conf
  #   ports:
  #     - 9324:9324
  #     - 9325:9325
