name: 'coverage'
on:
  pull_request:
    branches:
      - main
  push:
    # only trigger on branches, not on tags
    branches:
      - '**'
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          test-script: pnpm test